[package]
name = "yeti"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
walkdir = "2.3.2"
tera = "1.17.1"
path-absolutize = "3.0.14"